[package]
name = "bitbash"
version = "0.1.0"
authors = ["Alistair Geesing <alistair.geesing@icloud.com>"]
edition = "2018"

[dependencies]
bitbash-macros = { path = "../bitbash_macros" }

[features]
const = []
